services:
  backend:
    image: oven/bun:1.1.28
    working_dir: /app
    volumes:
      - ./backend:/app
    env_file:
      - .env
    environment:
      - DB_URL=http://db:8000/rpc
    expose:
      - 80
    ports:
      - 80:80
    command: bun run --hot index.ts
    depends_on:
      - db
    restart: always
  frontend:
    image: oven/bun:1.1.27
    working_dir: /app
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    ports:
      - 5173:80
    env_file:
      - .env
    command: bun run dev -- --host --port 80
  db:
    image: surrealdb/surrealdb:v2.0.0
    user: root
    expose:
      - 8000
    ports:
      - 8000:8000
    command: start --user root --pass root rocksdb://data/database.db
    volumes:
      - db:/data

volumes:
  db:
