name: Deploy

on: [push, pull_request]

jobs:
  deploy:
    name: "Deploy to server"
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    env:
      SSH_USER: ${{ secrets.PRODUCTION_SSH_USER }}
      SSH_KEY: ${{ secrets.PRODUCTION_SSH_KEY }}
      SSH_HOST: ${{ secrets.PRODUCTION_SSH_HOST }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/production.key
          chmod 600 ~/.ssh/production.key
          cat >>~/.ssh/config <<END
          Host production
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/production.key
            StrictHostKeyChecking no
          END
      - name: Copy
        run: |
          rsync -v -r --exclude .git --exclude .github --exclude compose.yml . production:/data/projects/netter
      - name: Deploy
        run: |
          ssh production "cd /data/projects/netter && docker compose -f compose.prod.yml stop && docker compose -f compose.prod.yml --build up -d"